### ISSUE TITLE
Cyrillic extension v1.500 hasn't been merged yet

### ISSUE THREAD

**Issue by alexeiva** [googlefonts/Libre-Franklin#20]
There is a Cyrillic component that hasn't been merged with original repo, so these two forkes have diverged. 

https://github.com/alexeiva/Libre-Franklin

**Comment by emmamarichal** [comment]
done @alexeiva!
I'm gonna push the update on the API soon! It's now the 3.000 version since it's a major update

**Comment by alexeiva** [comment]
Sounds great! Looking forward to the update
